name: Build and Deploy Client
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t antxoneguigurenperez/ci-cd-client --build-arg VITE_REACT_APP_NODE_ENV='production' --build-arg VITE_REACT_APP_SERVER_BASE_URL='${{secrets.REACT_APP_SERVER_BASE_URL}}'  .
      - name: Publish Image to DockerHub
        run: docker push antxoneguigurenperez/ci-cd-client:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image fom DockerHub
        run: docker pull antxoneguigurenperez/ci-cd-client:latest
      - name: Delete Old Container
        run: docker rm -f ci-cd-client-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name ci-cd-client-container antxoneguigurenperez/ci-cd-client
